version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env.dev

volumes:
  postgres_data:
