# Generated by Django 3.2.9 on 2022-01-16 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_basket_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='is_active',
        ),
    ]
