# Generated by Django 3.2.9 on 2021-12-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_userprofile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'english'), ('ru', 'русский')], default='ru', max_length=2, verbose_name='язык'),
        ),
    ]
